In [32]:
from nba_api.stats.endpoints import leaguestandings
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
standings = leaguestandings.LeagueStandings()
standings_data = standings.get_data_frames()[0]

In [34]:
print(len(standings.get_data_frames()))

1

In [35]:
# Head ( first 5 rows),
standings_data.head()

,LeagueID,SeasonID,TeamID,TeamCity,TeamName,Conference,ConferenceRecord,PlayoffRank,ClinchIndicator,Division,...,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,PreAS,PostAS
0,00,22024,1610612739,Cleveland,Cavaliers,East,23-5,1,,Central,...,None,None,None,None,None,5-0,12-3,12-1,34-6,None
1,00,22024,1610612760,Oklahoma City,Thunder,West,19-5,1,,Northwest,...,None,None,None,None,None,4-0,11-4,12-1,34-6,None
2,00,22024,1610612738,Boston,Celtics,East,22-8,2,,Atlantic,...,None,None,None,None,None,4-1,12-2,8-6,28-12,None
3,00,22024,1610612745,Houston,Rockets,West,18-8,2,,Southwest,...,None,None,None,None,None,3-2,11-4,7-5,27-12,None
4,00,22024,1610612752,New York,Knicks,East,20-10,3,,Atlantic,...,None,None,None,None,None,2-2,9-6,12-2,27-15,None

In [36]:
#Tail (last 5 rows)
standings_data.tail()

,LeagueID,SeasonID,TeamID,TeamCity,TeamName,Conference,ConferenceRecord,PlayoffRank,ClinchIndicator,Division,...,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,PreAS,PostAS
25,00,22024,1610612761,Toronto,Raptors,East,6-20,13,,Atlantic,...,None,None,None,None,None,1-4,4-11,2-11,10-31,None
26,00,22024,1610612762,Utah,Jazz,West,3-22,14,,Northwest,...,None,None,None,None,None,0-5,4-10,3-9,10-29,None
27,00,22024,1610612766,Charlotte,Hornets,East,6-24,14,,Southeast,...,None,None,None,None,None,2-2,4-12,1-11,9-28,None
28,00,22024,1610612740,New Orleans,Pelicans,West,4-19,15,,Southwest,...,None,None,None,None,None,2-3,2-13,1-12,10-32,None
29,00,22024,1610612764,Washington,Wizards,East,5-19,15,,Southeast,...,None,None,None,None,None,2-2,0-14,3-9,6-33,None

.info() - prints info about the dataframe

In [37]:
standings_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 81 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   LeagueID                 30 non-null     object
 1   SeasonID                 30 non-null     object
 2   TeamID                   30 non-null     int64
 3   TeamCity                 30 non-null     object
 4   TeamName                 30 non-null     object
 5   Conference               30 non-null     object
 6   ConferenceRecord         30 non-null     object
 7   PlayoffRank              30 non-null     int64
 8   ClinchIndicator          30 non-null     object
 9   Division                 30 non-null     object
 10  DivisionRecord           30 non-null     object
 11  DivisionRank             30 non-null     int64
 12  WINS                     30 non-null     int64
 13  LOSSES                   30 non-null     int64
 14  WinPCT                   30 non-null     float64
 15  LeagueRank               8 non-null      float64
 16  Record                   30 non-null     object
 17  HOME                     30 non-null     object
 18  ROAD                     30 non-null     object
 19  L10                      30 non-null     object
 20  Last10Home               30 non-null     object
 21  Last10Road               30 non-null     object
 22  OT                       30 non-null     object
 23  ThreePTSOrLess           30 non-null     object
 24  TenPTSOrMore             30 non-null     object
 25  LongHomeStreak           30 non-null     int64
 26  strLongHomeStreak        30 non-null     object
 27  LongRoadStreak           30 non-null     int64
 28  strLongRoadStreak        30 non-null     object
 29  LongWinStreak            30 non-null     int64
 30  LongLossStreak           30 non-null     int64
 31  CurrentHomeStreak        30 non-null     int64
 32  strCurrentHomeStreak     30 non-null     object
 33  CurrentRoadStreak        30 non-null     int64
 34  strCurrentRoadStreak     30 non-null     object
 35  CurrentStreak            30 non-null     int64
 36  strCurrentStreak         30 non-null     object
 37  ConferenceGamesBack      30 non-null     float64
 38  DivisionGamesBack        30 non-null     float64
 39  ClinchedConferenceTitle  30 non-null     int64
 40  ClinchedDivisionTitle    30 non-null     int64
 41  ClinchedPlayoffBirth     30 non-null     int64
 42  EliminatedConference     30 non-null     int64
 43  EliminatedDivision       30 non-null     int64
 44  AheadAtHalf              30 non-null     object
 45  BehindAtHalf             30 non-null     object
 46  TiedAtHalf               30 non-null     object
 47  AheadAtThird             30 non-null     object
 48  BehindAtThird            30 non-null     object
 49  TiedAtThird              30 non-null     object
 50  Score100PTS              30 non-null     object
 51  OppScore100PTS           30 non-null     object
 52  OppOver500               30 non-null     object
 53  LeadInFGPCT              30 non-null     object
 54  LeadInReb                30 non-null     object
 55  FewerTurnovers           30 non-null     object
 56  PointsPG                 30 non-null     float64
 57  OppPointsPG              30 non-null     float64
 58  DiffPointsPG             30 non-null     float64
 59  vsEast                   30 non-null     object
 60  vsAtlantic               30 non-null     object
 61  vsCentral                30 non-null     object
 62  vsSoutheast              30 non-null     object
 63  vsWest                   30 non-null     object
 64  vsNorthwest              30 non-null     object
 65  vsPacific                30 non-null     object
 66  vsSouthwest              30 non-null     object
 67  Jan                      30 non-null     object
 68  Feb                      0 non-null      object
 69  Mar                      0 non-null      object
 70  Apr                      0 non-null      object
 71  May                      0 non-null      object
 72  Jun                      0 non-null      object
 73  Jul                      0 non-null      object
 74  Aug                      0 non-null      object
 75  Sep                      0 non-null      object
 76  Oct                      30 non-null     object
 77  Nov                      30 non-null     object
 78  Dec                      30 non-null     object
 79  PreAS                    30 non-null     object
 80  PostAS                   0 non-null      object
dtypes: float64(7), int64(17), object(57)
memory usage: 19.1+ KB

.shape - dimensions of the data frame

In [38]:
standings_data.shape

(30, 81)

.describe() - describes the data frame i.e a summary.

In [39]:
standings_data.describe()

,TeamID,PlayoffRank,DivisionRank,WINS,LOSSES,WinPCT,LeagueRank,LongHomeStreak,LongRoadStreak,LongWinStreak,...,ConferenceGamesBack,DivisionGamesBack,ClinchedConferenceTitle,ClinchedDivisionTitle,ClinchedPlayoffBirth,EliminatedConference,EliminatedDivision,PointsPG,OppPointsPG,DiffPointsPG
count,3.000000e+01,30.000000,30.00000,30.000000,30.00000,30.000000,8.000000,30.000000,30.000000,30.000000,...,30.000000,30.000000,30.0,30.0,30.0,30.0,30.0,30.000000,30.00000,30.000000
mean,1.610613e+09,8.000000,3.00000,20.000000,20.00000,0.499267,2.500000,2.566667,-1.266667,5.466667,...,14.000000,8.000000,0.0,0.0,0.0,0.0,0.0,112.913333,112.94000,-0.023333
std,8.803408e+00,4.394354,1.43839,6.878252,6.71591,0.170047,1.195229,6.134601,6.689845,3.191944,...,6.769608,7.441728,0.0,0.0,0.0,0.0,0.0,4.664964,4.57313,6.182494
min,1.610613e+09,1.000000,1.00000,6.000000,6.00000,0.154000,1.000000,-10.000000,-15.000000,2.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,104.500000,103.60000,-14.100000
25%,1.610613e+09,4.250000,2.00000,15.750000,17.00000,0.398500,1.750000,-1.500000,-6.000000,3.250000,...,11.500000,1.125000,0.0,0.0,0.0,0.0,0.0,109.500000,110.85000,-3.475000
50%,1.610613e+09,8.000000,3.00000,21.000000,19.00000,0.519000,2.500000,4.000000,-0.500000,5.000000,...,13.250000,7.000000,0.0,0.0,0.0,0.0,0.0,111.900000,112.85000,0.350000
75%,1.610613e+09,11.750000,4.00000,23.000000,23.75000,0.564000,3.250000,7.000000,4.000000,6.750000,...,18.000000,13.375000,0.0,0.0,0.0,0.0,0.0,116.475000,115.80000,3.200000
max,1.610613e+09,15.000000,5.00000,34.000000,33.00000,0.850000,4.000000,10.000000,8.000000,15.000000,...,27.500000,23.500000,0.0,0.0,0.0,0.0,0.0,123.000000,122.80000,13.000000

In [40]:
from nba_api.stats.endpoints import commonteamroster

# Toronto Raptors Team ID and the current season
team_id = 1610612761  # Toronto Raptors
season = '2024-25'    # Use the current NBA season in "YYYY-YY" format

# Fetch roster for the current season
team_roster = commonteamroster.CommonTeamRoster(team_id=team_id, season=season)
roster_df = team_roster.get_data_frames()[0]

roster_df

,TeamID,SEASON,LeagueID,PLAYER,NICKNAME,PLAYER_SLUG,NUM,POSITION,HEIGHT,WEIGHT,BIRTH_DATE,AGE,EXP,SCHOOL,PLAYER_ID,HOW_ACQUIRED
0,1610612761,2024,00,A.J. Lawson,A.J.,aj-lawson,0,G,6-6,179,"JUL 15, 2000",24.0,2,South Carolina,1630639,Signed on 12/11/24
1,1610612761,2024,00,Gradey Dick,Gradey,gradey-dick,1,G-F,6-6,200,"NOV 20, 2003",21.0,1,Kansas,1641711,#13 Pick in 2023 Draft
2,1610612761,2024,00,Jonathan Mogbo,Jonathan,jonathan-mogbo,2,F,6-9,225,"OCT 29, 2001",23.0,R,San Francisco,1642367,#31 Pick in 2024 Draft
3,1610612761,2024,00,Scottie Barnes,Scottie,scottie-barnes,4,F-G,6-7,237,"AUG 01, 2001",23.0,3,Florida State,1630567,#4 Pick in 2021 Draft
4,1610612761,2024,00,Immanuel Quickley,Immanuel,immanuel-quickley,5,G,6-2,190,"JUN 17, 1999",25.0,4,Kentucky,1630193,Traded from NYK on 12/30/23
5,1610612761,2024,00,RJ Barrett,RJ,rj-barrett,9,F-G,6-6,214,"JUN 14, 2000",24.0,5,Duke,1629628,Traded from NYK on 12/30/23
6,1610612761,2024,00,Bruce Brown,Bruce,bruce-brown,11,G-F,6-4,202,"AUG 15, 1996",28.0,6,Miami,1628971,Traded from IND on 01/17/24
7,1610612761,2024,00,Ja'Kobe Walter,Ja'Kobe,jakobe-walter,14,G,6-5,180,"SEP 04, 2004",20.0,R,Baylor,1642266,#19 Pick in 2024 Draft
8,1610612761,2024,00,Garrett Temple,Garrett,garrett-temple,17,G-F,6-5,195,"MAY 08, 1986",38.0,14,Louisiana State,202066,Signed on 07/31/23
9,1610612761,2024,00,Jakob Poeltl,Jakob,jakob-poeltl,19,C,7-0,260,"OCT 15, 1995",29.0,8,Utah,1627751,Traded from SAS on 02/09/23
10,1610612761,2024,00,Ulrich Chomche,Ulrich,ulrich-chomche,22,C,6-11,235,"DEC 30, 2005",19.0,R,NBA Global Academy,1642279,Draft Rights Traded from MEM on 07/06/24
11,1610612761,2024,00,Jamal Shead,Jamal,jamal-shead,23,G,6-1,200,"JUL 24, 2002",22.0,R,Houston,1642347,Draft Rights Traded from SAC on 06/28/24
12,1610612761,2024,00,Chris Boucher,Chris,chris-boucher,25,F,6-9,200,"JAN 11, 1993",32.0,7,Oregon,1628449,Signed on 07/20/18
13,1610612761,2024,00,Ochai Agbaji,Ochai,ochai-agbaji,30,G,6-5,215,"APR 20, 2000",24.0,2,Kansas,1630534,Traded from UTA on 02/08/24
14,1610612761,2024,00,Kelly Olynyk,Kelly,kelly-olynyk,41,F-C,6-11,240,"APR 19, 1991",33.0,11,Gonzaga,203482,Traded from UTA on 02/08/24
15,1610612761,2024,00,Davion Mitchell,Davion,davion-mitchell,45,G,6-0,202,"SEP 05, 1998",26.0,3,Baylor,1630558,Traded from SAC on 06/28/24
16,1610612761,2024,00,Jamison Battle,Jamison,jamison-battle,77,F,6-7,220,"MAY 10, 2001",23.0,R,Ohio State,1642419,Signed on 07/16/24
17,1610612761,2024,00,Eugene Omoruyi,Eugene,eugene-omoruyi,97,F,6-6,235,"FEB 14, 1997",27.0,3,Oregon,1630647,Signed on 01/08/25

In [41]:
roster_df = roster_df.drop(columns="HOW_ACQUIRED")

In [42]:
roster_df # removed how acquired

,TeamID,SEASON,LeagueID,PLAYER,NICKNAME,PLAYER_SLUG,NUM,POSITION,HEIGHT,WEIGHT,BIRTH_DATE,AGE,EXP,SCHOOL,PLAYER_ID
0,1610612761,2024,00,A.J. Lawson,A.J.,aj-lawson,0,G,6-6,179,"JUL 15, 2000",24.0,2,South Carolina,1630639
1,1610612761,2024,00,Gradey Dick,Gradey,gradey-dick,1,G-F,6-6,200,"NOV 20, 2003",21.0,1,Kansas,1641711
2,1610612761,2024,00,Jonathan Mogbo,Jonathan,jonathan-mogbo,2,F,6-9,225,"OCT 29, 2001",23.0,R,San Francisco,1642367
3,1610612761,2024,00,Scottie Barnes,Scottie,scottie-barnes,4,F-G,6-7,237,"AUG 01, 2001",23.0,3,Florida State,1630567
4,1610612761,2024,00,Immanuel Quickley,Immanuel,immanuel-quickley,5,G,6-2,190,"JUN 17, 1999",25.0,4,Kentucky,1630193
5,1610612761,2024,00,RJ Barrett,RJ,rj-barrett,9,F-G,6-6,214,"JUN 14, 2000",24.0,5,Duke,1629628
6,1610612761,2024,00,Bruce Brown,Bruce,bruce-brown,11,G-F,6-4,202,"AUG 15, 1996",28.0,6,Miami,1628971
7,1610612761,2024,00,Ja'Kobe Walter,Ja'Kobe,jakobe-walter,14,G,6-5,180,"SEP 04, 2004",20.0,R,Baylor,1642266
8,1610612761,2024,00,Garrett Temple,Garrett,garrett-temple,17,G-F,6-5,195,"MAY 08, 1986",38.0,14,Louisiana State,202066
9,1610612761,2024,00,Jakob Poeltl,Jakob,jakob-poeltl,19,C,7-0,260,"OCT 15, 1995",29.0,8,Utah,1627751
10,1610612761,2024,00,Ulrich Chomche,Ulrich,ulrich-chomche,22,C,6-11,235,"DEC 30, 2005",19.0,R,NBA Global Academy,1642279
11,1610612761,2024,00,Jamal Shead,Jamal,jamal-shead,23,G,6-1,200,"JUL 24, 2002",22.0,R,Houston,1642347
12,1610612761,2024,00,Chris Boucher,Chris,chris-boucher,25,F,6-9,200,"JAN 11, 1993",32.0,7,Oregon,1628449
13,1610612761,2024,00,Ochai Agbaji,Ochai,ochai-agbaji,30,G,6-5,215,"APR 20, 2000",24.0,2,Kansas,1630534
14,1610612761,2024,00,Kelly Olynyk,Kelly,kelly-olynyk,41,F-C,6-11,240,"APR 19, 1991",33.0,11,Gonzaga,203482
15,1610612761,2024,00,Davion Mitchell,Davion,davion-mitchell,45,G,6-0,202,"SEP 05, 1998",26.0,3,Baylor,1630558
16,1610612761,2024,00,Jamison Battle,Jamison,jamison-battle,77,F,6-7,220,"MAY 10, 2001",23.0,R,Ohio State,1642419
17,1610612761,2024,00,Eugene Omoruyi,Eugene,eugene-omoruyi,97,F,6-6,235,"FEB 14, 1997",27.0,3,Oregon,1630647

Next, we will do itterows() to iterate over each row in the data frame

In [43]:
from nba_api.stats.endpoints import playergamelog

Testing on Lebron James

In [44]:
gamelog = playergamelog.PlayerGameLog(player_id=2544) #testing on lebron
data = gamelog.get_data_frames()[0]
print(len(gamelog.get_data_frames()))
data

1

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22024,2544,0022400570,"JAN 15, 2025",LAL vs. MIA,W,38,9,15,0.600,...,4,5,9,2,0,2,0,22,14,1
1,22024,2544,0022400552,"JAN 13, 2025",LAL vs. SAS,L,32,7,11,0.636,...,4,5,8,1,1,7,3,18,-15,1
2,22024,2544,0022400504,"JAN 07, 2025",LAL @ DAL,L,35,6,12,0.500,...,10,10,8,1,0,2,0,18,-12,1
3,22024,2544,0022400491,"JAN 05, 2025",LAL @ HOU,L,36,8,16,0.500,...,12,13,9,1,0,2,4,21,-13,1
4,22024,2544,0022400477,"JAN 03, 2025",LAL vs. ATL,W,30,13,20,0.650,...,3,3,8,0,0,3,3,30,4,1
5,22024,2544,0022400468,"JAN 02, 2025",LAL vs. POR,W,36,15,25,0.600,...,2,3,8,0,0,4,1,38,4,1
6,22024,2544,0022400454,"DEC 31, 2024",LAL vs. CLE,L,34,9,17,0.529,...,4,4,7,0,1,2,1,23,-11,1
7,22024,2544,0022400408,"DEC 25, 2024",LAL @ GSW,W,37,12,22,0.545,...,4,4,10,2,1,1,3,31,4,1
8,22024,2544,0022400404,"DEC 23, 2024",LAL vs. DET,L,35,10,16,0.625,...,9,11,11,0,0,2,1,28,-1,1
9,22024,2544,0022400376,"DEC 21, 2024",LAL @ SAC,W,34,13,24,0.542,...,7,7,6,4,0,4,2,32,10,1
10,22024,2544,0022400372,"DEC 19, 2024",LAL @ SAC,W,34,8,21,0.381,...,6,6,7,0,1,2,1,19,13,1
11,22024,2544,0022401220,"DEC 15, 2024",LAL vs. MEM,W,34,7,17,0.412,...,4,8,8,1,2,5,2,18,0,1
12,22024,2544,0022400334,"DEC 06, 2024",LAL @ ATL,L,43,14,25,0.560,...,10,10,11,2,3,4,3,39,3,1
13,22024,2544,0022400321,"DEC 04, 2024",LAL @ MIA,L,29,12,18,0.667,...,4,5,8,1,0,5,2,29,-21,1
14,22024,2544,0022400318,"DEC 02, 2024",LAL @ MIN,L,31,4,16,0.250,...,5,8,4,0,0,6,1,10,-28,1
15,22024,2544,0022400311,"DEC 01, 2024",LAL @ UTA,W,36,12,28,0.429,...,4,5,14,0,2,3,1,27,0,1
16,22024,2544,0022400048,"NOV 29, 2024",LAL vs. OKC,L,34,5,13,0.385,...,8,8,6,0,0,5,0,12,-12,1
17,22024,2544,0022400296,"NOV 27, 2024",LAL @ SAS,W,33,8,18,0.444,...,7,10,11,1,1,5,0,16,4,1
18,22024,2544,0022400039,"NOV 26, 2024",LAL @ PHX,L,35,7,16,0.438,...,7,8,10,0,0,5,0,18,-30,1
19,22024,2544,0022400270,"NOV 23, 2024",LAL vs. DEN,L,35,7,17,0.412,...,6,6,7,3,0,6,3,18,-25,1
20,22024,2544,0022400263,"NOV 21, 2024",LAL vs. ORL,L,37,12,22,0.545,...,8,10,7,0,1,4,0,31,-8,1
21,22024,2544,0022400026,"NOV 19, 2024",LAL vs. UTA,W,34,9,17,0.529,...,2,2,12,0,0,4,1,26,-5,1
22,22024,2544,0022400231,"NOV 16, 2024",LAL @ NOP,W,37,8,19,0.421,...,3,7,5,1,0,6,1,21,1,1
23,22024,2544,0022400015,"NOV 15, 2024",LAL @ SAS,W,38,6,12,0.500,...,15,16,12,1,0,7,0,15,3,1
24,22024,2544,0022400225,"NOV 13, 2024",LAL vs. MEM,W,37,13,22,0.591,...,11,12,14,1,0,6,2,35,3,1
25,22024,2544,0022400211,"NOV 10, 2024",LAL vs. TOR,W,35,6,14,0.429,...,8,10,16,1,0,3,0,19,13,1
26,22024,2544,0022400195,"NOV 08, 2024",LAL vs. PHI,W,34,9,14,0.643,...,12,12,13,0,3,2,0,21,12,1
27,22024,2544,0022400174,"NOV 06, 2024",LAL @ MEM,L,35,15,24,0.625,...,7,7,6,1,0,5,2,39,-21,1
28,22024,2544,0022400156,"NOV 04, 2024",LAL @ DET,L,40,7,16,0.438,...,7,8,11,2,0,1,1,20,-16,1
29,22024,2544,0022400137,"NOV 01, 2024",LAL @ TOR,W,36,9,17,0.529,...,6,6,10,1,0,0,1,27,11,1
30,22024,2544,0022400118,"OCT 30, 2024",LAL @ CLE,L,29,9,13,0.692,...,5,6,3,0,0,6,2,26,-17,1
31,22024,2544,0022400111,"OCT 28, 2024",LAL @ PHX,L,36,3,14,0.214,...,5,5,8,1,0,2,1,11,-17,1
32,22024,2544,0022400096,"OCT 26, 2024",LAL vs. SAC,W,34,12,22,0.545,...,14,14,10,0,1,5,3,32,13,1
33,22024,2544,0022400085,"OCT 25, 2024",LAL vs. PHX,W,35,7,13,0.538,...,4,4,8,0,0,2,1,21,14,1
34,22024,2544,0022400062,"OCT 22, 2024",LAL vs. MIN,W,35,7,16,0.438,...,5,5,4,0,2,2,3,16,-6,1

In [45]:
player_data = []
for index, row in roster_df.iterrows():
    player_id = row["PLAYER_ID"]
    player_name = row["PLAYER"]
    try:
        gamelog = playergamelog.PlayerGameLog(player_id=player_id)
        data = gamelog.get_data_frames()[0]
        if not data.empty:
            data['PLAYER'] = player_name
            player_data.append(data)
    except Exception as e:
        print(f"Error fetching data for {player_name}: {e}")
toronto_raptors_data = pd.concat(player_data, ignore_index=True)
toronto_raptors_data

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,PLAYER
0,22024,1630639,0022400449,"DEC 31, 2024",TOR @ BOS,L,4,0,3,0.000,...,1,0,0,0,0,0,0,-8,1,A.J. Lawson
1,22024,1630639,0022400414,"DEC 26, 2024",TOR @ MEM,L,5,2,3,0.667,...,2,0,0,0,0,0,6,-4,1,A.J. Lawson
2,22024,1630639,0022400397,"DEC 23, 2024",TOR @ NYK,L,4,1,1,1.000,...,0,0,0,0,0,0,3,5,1,A.J. Lawson
3,22024,1641711,0022400562,"JAN 15, 2025",TOR vs. BOS,W,25,4,9,0.444,...,3,4,0,0,1,2,12,5,1,Gradey Dick
4,22024,1641711,0022400550,"JAN 13, 2025",TOR vs. GSW,W,23,4,10,0.400,...,3,1,0,0,1,1,12,-10,1,Gradey Dick
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,22024,1642419,0022400117,"OCT 30, 2024",TOR @ CHA,L,14,0,2,0.000,...,3,0,0,0,0,2,0,-19,1,Jamison Battle
422,22024,1642419,0022400107,"OCT 28, 2024",TOR vs. DEN,L,12,1,3,0.333,...,1,0,0,1,0,3,4,3,1,Jamison Battle
423,22024,1642419,0022400093,"OCT 26, 2024",TOR @ MIN,L,19,3,8,0.375,...,6,1,0,0,0,0,9,4,1,Jamison Battle
424,22024,1642419,0022400078,"OCT 25, 2024",TOR vs. PHI,W,15,4,5,0.800,...,6,0,0,0,0,6,12,4,1,Jamison Battle
425,22024,1642419,0022400067,"OCT 23, 2024",TOR vs. CLE,L,16,2,4,0.500,...,2,1,0,1,0,1,6,0,1,Jamison Battle

In [46]:
# Creating a new dataframe
consistency_data = toronto_raptors_data.groupby('PLAYER').agg(
    GAMES_PLAYED=('Game_ID', 'count'),
    PTS_MEAN=('PTS', 'mean'),
    PTS_STD=('PTS', 'std'))
consistency_data['CONSISTENCY'] = consistency_data['PTS_STD'] / consistency_data['PTS_MEAN']
consistency_data = consistency_data.sort_values(by='CONSISTENCY', ascending=True)

Now the top five most consistent players on the Toronto Raptors are...

In [47]:
consistency_data.head()

                   GAMES_PLAYED   PTS_MEAN   PTS_STD  CONSISTENCY
PLAYER
Scottie Barnes               28  20.285714  6.531163     0.321959
RJ Barrett                   33  22.424242  7.790340     0.347407
Immanuel Quickley             9  16.222222  5.890199     0.363094
Gradey Dick                  35  16.200000  7.638140     0.471490
Jakob Poeltl                 36  14.861111  7.306173     0.491630